### ISSUE TITLE
Bazel --incompatible_depset_is_not_iterable

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/rules_webtesting#329]
Hi,

It looks like this project cannot build with the Bazel flag `--incompatible_depset_is_not_iterable`.
Logs (https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/28#2d632a4f-bd90-4e5d-be99-954b500efb8d):

```
ERROR: /var/lib/buildkite-agent/builds/bk-docker-d6ch/bazel-downstream-projects/rules_webtesting/testdata/BUILD.bazel:29:1: in web_test_files rule //testdata:keys:
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/bk-docker-d6ch/bazel-downstream-projects/rules_webtesting/testdata/BUILD.bazel", line 29
  | web_test_files(name = 'keys')
  | File "/var/lib/buildkite-agent/builds/bk-docker-d6ch/bazel-downstream-projects/rules_webtesting/web/internal/web_test_files.bzl", line 29, in _web_test_files_impl
  | len(target.files)
  | depset is not iterable. You may use `len(<depset>.to_list())` instead. Use --incompatible_depset_is_not_iterable=false to temporarily disable this check.
```

Could you take a look?
Depset documentation: https://docs.bazel.build/versions/master/skylark/depsets.html

Let me know if you need any help

**Comment by laurentlb** [comment]
Any update?

cc @DrMarcII
