### ISSUE TITLE
Unable to fetch 'io_bazel_rules_webtesting' repository due to updated hashes

### ISSUE THREAD

**Issue by qaiffluke** [bazelbuild/rules_webtesting#388]
I'm a newbie at Bazel and everything was working fine until only recently have I come across this problem. Any help would be appreciated.

````
INFO: Repository 'io_bazel_rules_webtesting' used the following cache hits instead of downloading the corresponding file.
 * Hash 'f1f4d2c2f88d2beac64c82499a1e762b037966675dd892da89c87e39d72b33f6' for https://github.com/bazelbuild/rules_webtesting/releases/download/0.3.2/rules_webtesting.tar.gz
If the definition of 'io_bazel_rules_webtesting' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_webtesting':
   Traceback (most recent call last):
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
                patch(ctx)
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 81, in patch
                "{patchtool} {patch_args} < {patchfile}".format(patchtool = ctx.attr.patch_tool, p...), ...]))
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 83, in "{patchtool} {patch_args} < {patchfile}".format
                ctx.path(patchfile)
Not a regular file: C:/users/bazel_user/vqxrcad2/external/build_bazel_rules_nodejs/rules_webtesting.patch
ERROR: no such package '@io_bazel_rules_webtesting//web': Traceback (most recent call last):
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
                patch(ctx)
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 81, in patch
                "{patchtool} {patch_args} < {patchfile}".format(patchtool = ctx.attr.patch_tool, p...), ...]))
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 83, in "{patchtool} {patch_args} < {patchfile}".format
                ctx.path(patchfile)
Not a regular file: C:/users/bazel_user/vqxrcad2/external/build_bazel_rules_nodejs/rules_webtesting.patch
ERROR: no such package '@io_bazel_rules_webtesting//web': Traceback (most recent call last):
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/http.bzl", line 56
                patch(ctx)
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 81, in patch
                "{patchtool} {patch_args} < {patchfile}".format(patchtool = ctx.attr.patch_tool, p...), ...]))
        File "C:/users/bazel_user/vqxrcad2/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 83, in "{patchtool} {patch_args} < {patchfile}".format
                ctx.path(patchfile)
Not a regular file: C:/users/bazel_user/vqxrcad2/external/build_bazel_rules_nodejs/rules_webtesting.patch
````

I have tried the following workaround too:
```
http_archive(
    name = "io_bazel_rules_webtesting",
    url = "https://github.com/bazelbuild/rules_webtesting/archive/ca7b8062d9cf4ef2fde9193c7d37a0764c4262d7.zip",
    strip_prefix = "rules_webtesting-ca7b8062d9cf4ef2fde9193c7d37a0764c4262d7",
    sha256 = "28c73cf9d310fa6dba30e66bdb98071341c99c3feb8662f2d3883a632de97d72",
)
```

But it gives me the same error. However, if I move it before loading the `rules_karma_dependencies`, it wants me to include the go_dependencies which I do not need.

All suggestions are welcome and please let me know if this is the right place to report this or someplace else. 
Thank you!!

**Comment by DrMarcII** [comment]
In general you should be using the released versions as follows:
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "io_bazel_rules_webtesting",
    sha256 = "f1f4d2c2f88d2beac64c82499a1e762b037966675dd892da89c87e39d72b33f6",
    urls = [
        "https://github.com/bazelbuild/rules_webtesting/releases/download/0.3.2/rules_webtesting.tar.gz",
    ],
)

load("@io_bazel_rules_webtesting//web:repositories.bzl", "web_test_repositories")

web_test_repositories()

Otherwise you will need the go dependencies (the released version includes precompiled binaries).

**Comment by johnnysainz** [comment]
Having the same problem as @qaiffluke. Following @DrMarcII's advice does not resolve this for me. Is there an order in which the http_archive, load, and web_test_repositories() must appear within the WORKSPACE file for this to work properly?

**Comment by qaiffluke** [comment]
Following the advice @DrMarcII gave, worked for me. But I've been getting a new error instead:
```
ERROR: error loading package '': in C:/users/bazel_user/external/npm_bazel_typescript/defs.bzl: in C:/users/bazel_user/external/npm_bazel_typescript/internal/build_defs.bzl: in C:/
users/bazel_user/external/npm_bazel_typescript/internal/common/compilation.bzl: Unable to load file '@build_bazel_rules_nodejs//:declaration_provider.bzl': file doesn't exist
ERROR: error loading package '': in C:/users/bazel_user/external/npm_bazel_typescript/defs.bzl: in C:/users/bazel_user/external/npm_bazel_typescript/internal/build_defs.bzl: in C:/
users/bazel_user/external/npm_bazel_typescript/internal/common/compilation.bzl: Unable to load file '@build_bazel_rules_nodejs//:declaration_provider.bzl': file doesn't exist
```
I don't understand what is wrong. I've been following the [angular-bazel-example](https://github.com/angular/angular-bazel-example) for reference. 
Can you help me understand the problem here?
Thank you!
